[package]
name = "stylish_webrender"
version = "0.1.0"
authors = ["Matthew Collins <thethinkofdeath@gmail.com>"]

[dependencies]
stylish = { path = "../" }
gleam = "0.4.3"
app_units = "0.5"
stb_truetype = "0.2.1"
euclid = "0.15"

[dev-dependencies]
glutin = "0.9"
image = "0.13.0"

[dependencies.webrender]
git = "https://github.com/servo/webrender"
rev = "101c69db1a989fe89c308dabd53cf50aedfe4a96"
default-features = false
features = [ "freetype-lib" ]
