[package]
authors = ["Matthew Collins <thethinkofdeath@gmail.com>"]
name = "stylish"
version = "0.1.0"

[dependencies]
error-chain = "0.12.0"
fnv = "1.0.6"

[dependencies.stylish_syntax]
path = "./syntax"

[workspace]
members = [
    "./syntax",
    "./webrender",
]
